### ISSUE TITLE
Add configuration and sample to accept TraceID headers

### ISSUE THREAD

**Issue by salrashid123** [salrashid123/fluent-plugin-envoy-parser#1]
Specifically for GCP, the [X-Cloud-Trace-Context](https://cloud.google.com/trace/docs/troubleshooting#force-trace)  header for the `http_filter` should get extracted and place into the `trace` field for the GCP [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry).

--

---
the envoy config for the http filter that extracts the header and places it the last filed here:
``` \"%REQ(X-Cloud-Trace-Context)%\"```

```yaml
- name: envoy.file_access_log
  config:
    path: "/var/log/envoy.log"
    #path: "/dev/stdout"
    format: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)
%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" \"%REQ(X-Cloud-Trace-Context)%\"\n"
```
